# Configuration File for tcpsh Server
name = "tcpsh Server" # Server Name
bufsize = 4096 # recv() buffer size

[auth]
authorized_certificates = "authorized_certs/" # Directory containing the certificates of clients that should be allowed to connect to this tcpsh server

[bind]
ip = ""
port = 3750

[ssl]
key = "s_key.pem"
cert = "s_cert.pem"
